<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Handwritten-Digit-Recognition" data-toc-modified-id="Handwritten-Digit-Recognition-1">Handwritten Digit Recognition</a></span><ul class="toc-item"><li><span><a href="#Check-the-shape-of-our-dataset" data-toc-modified-id="Check-the-shape-of-our-dataset-1.1">Check the shape of our dataset</a></span></li></ul></li><li><span><a href="#Splitting-the-dataset-for-training-and-testing" data-toc-modified-id="Splitting-the-dataset-for-training-and-testing-2">Splitting the dataset for training and testing</a></span></li><li><span><a href="#Model-Training" data-toc-modified-id="Model-Training-3">Model Training</a></span></li></ul></div>

# Handwritten Digit Recognition 

> First perform `dimensionality reduction` and then apply `Support Vector Machine` algorithm to get the accuracy.

In [1]:
#Importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import svm
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import time

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [2]:
#Importing the datasets

train = pd.read_csv("/Users/ankitsharma/Documents/Documents/Stuff/Minor Project/data/train.csv")
test = pd.read_csv("/Users/ankitsharma/Documents/Documents/Stuff/Minor Project/data/test.csv")

In [3]:
train.head(5)

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 785 columns]

In [4]:
test.head(5)

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9    ...     pixel774  pixel775  pixel776  pixel777  pixel778  \
0       0    ...            0         0         0         0         0   
1       0    ...            0         0         0         0         0   
2       0    ...            0         0         0         0         0   
3       0    ...            0         0         0         0         0   
4       0    ...            0         0         0         0         0   

   pixel779  pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0         0  
1         0         0         0         0         0  
2         0         0         0         0         0  
3         0         0         0         0         0  
4         0         0         0         0         0  

[5 rows x 784 columns]

In [5]:
train.shape

(42000, 785)

In [6]:
test.shape

(28000, 784)

In [7]:
#Splitting target class and independent variables

train_image = train.iloc[:, 1:]
train_label = train.iloc[:, 0]

In [8]:
train_image

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0           0       0       0       0       0       0       0       0       0   
1           0       0       0       0       0       0       0       0       0   
2           0       0       0       0       0       0       0       0       0   
3           0       0       0       0       0       0       0       0       0   
4           0       0       0       0       0       0       0       0       0   
5           0       0       0       0       0       0       0       0       0   
6           0       0       0       0       0       0       0       0       0   
7           0       0       0       0       0       0       0       0       0   
8           0       0       0       0       0       0       0       0       0   
9           0       0       0       0       0       0       0       0       0   
10          0       0       0       0       0       0       0       0       0   
11          0       0       0       0       0       0       0       0       0   
12          0       0       0       0       0       0       0       0       0   
13          0       0       0       0       0       0       0       0       0   
14          0       0       0       0       0       0       0       0       0   
15          0       0       0       0       0       0       0       0       0   
16          0       0       0       0       0       0       0       0       0   
17          0       0       0       0       0       0       0       0       0   
18          0       0       0       0       0       0       0       0       0   
19          0       0       0       0       0       0       0       0       0   
20          0       0       0       0       0       0       0       0       0   
21          0       0       0       0       0       0       0       0       0   
22          0       0       0       0       0       0       0       0       0   
23          0       0       0       0       0       0       0       0       0   
24          0       0       0       0       0       0       0       0       0   
25          0       0       0       0       0       0       0       0       0   
26          0       0       0       0       0       0       0       0       0   
27          0       0       0       0       0       0       0       0       0   
28          0       0       0       0       0       0       0       0       0   
29          0       0       0       0       0       0       0       0       0   
...       ...     ...     ...     ...     ...     ...     ...     ...     ...   
41970       0       0       0       0       0       0       0       0       0   
41971       0       0       0       0       0       0       0       0       0   
41972       0       0       0       0       0       0       0       0       0   
41973       0       0       0       0       0       0       0       0       0   
41974       0       0       0       0       0       0       0       0       0   
41975       0       0       0       0       0       0       0       0       0   
41976       0       0       0       0       0       0       0       0       0   
41977       0       0       0       0       0       0       0       0       0   
41978       0       0       0       0       0       0       0       0       0   
41979       0       0       0       0       0       0       0       0       0   
41980       0       0       0       0       0       0       0       0       0   
41981       0       0       0       0       0       0       0       0       0   
41982       0       0       0       0       0       0       0       0       0   
41983       0       0       0       0       0       0       0       0       0   
41984       0       0       0       0       0       0       0       0       0   
41985       0       0       0       0       0       0       0       0       0   
41986       0       0       0       0       0       0       0       0       0   
41987       0       0       0       0 

In [9]:
#scaling our dataset
train_image = train_image.values / 255.0
test_image = test.values / 255.0

In [10]:
train_image

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [11]:
train_label = train_label.values

In [12]:
train_label

array([1, 0, 1, ..., 7, 6, 9])

## Check the shape of our dataset



In [17]:
print("The shape of train_image: , train_label: ", train_image.shape, train_label.shape)

print("The shape of test_image: ", test_image.shape)

The shape of train_image: , train_label:  (42000, 784) (42000,)
The shape of test_image:  (28000, 784)


# Splitting the dataset for training and testing

In [18]:
X_train, X_val, y_train, y_val = train_test_split(train_image, train_label, train_size = 0.8, random_state = 0)

/usr/local/Cellar/python3/3.6.4_2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [19]:
X_train.shape

(33600, 784)

* Size of X_train reduced to 80% of the dataset and remaining 20% for testing..

In [20]:
X_val.shape

(8400, 784)

# Model Training

In [21]:
# Create a function for PCA and SVM

def n_component_analysis(n, X_train, y_train, X_val, y_val):
    start = time.time()
    pca = PCA(n_components=n)
    print("PCA analysis begins with components: ", n)
    
    pca.fit(X_train) #reduces dimensions
    X_train_pca = pca.transform(X_train)
    X_val_pca = pca.transform(X_val)
        
    print("Starting SVM")
    classifier = svm.SVC()
    classifier.fit(X_train_pca, y_train)
    
    accuracy = classifier.score(X_val_pca, y_val)
    
    end = time.time()
    
    print("accuracy: ", accuracy, "time elapsed: ", int(end-start))

In [22]:
model_running = np.linspace(0.70, 0.85, num=15)
accuracy = []

for n in model_running:
    temp = n_component_analysis(n, X_train, y_train, X_val, y_val)
    accuracy.append(temp)

PCA analysis begins with components:  0.7
Starting SVM
accuracy:  0.97869047619 time elapsed:  22
PCA analysis begins with components:  0.710714285714
Starting SVM
accuracy:  0.979166666667 time elapsed:  20
PCA analysis begins with components:  0.721428571429
Starting SVM
accuracy:  0.979404761905 time elapsed:  21
PCA analysis begins with components:  0.732142857143
Starting SVM
accuracy:  0.979404761905 time elapsed:  22
PCA analysis begins with components:  0.742857142857
Starting SVM
accuracy:  0.980119047619 time elapsed:  22
PCA analysis begins with components:  0.753571428571
Starting SVM
accuracy:  0.979761904762 time elapsed:  23
PCA analysis begins with components:  0.764285714286
Starting SVM
accuracy:  0.979880952381 time elapsed:  24
PCA analysis begins with components:  0.775
Starting SVM
accuracy:  0.979166666667 time elapsed:  24
PCA analysis begins with components:  0.785714285714
Starting SVM
accuracy:  0.97880952381 time elapsed:  25
PCA analysis begins with compone

In [27]:
pca = PCA(n_components = 0.75)
pca.fit(X_train)

PCA(copy=True, iterated_power='auto', n_components=0.75, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [28]:
pca.n_components_

33

In [29]:
pca.explained_variance_ratio_

array([ 0.09745105,  0.0711566 ,  0.06179298,  0.05376763,  0.04894433,
        0.04284305,  0.03270905,  0.02892718,  0.02767062,  0.0235005 ,
        0.02104833,  0.02067582,  0.01716195,  0.01699172,  0.01584733,
        0.01478364,  0.01319522,  0.01283561,  0.01185388,  0.01148943,
        0.01070532,  0.0101494 ,  0.00962151,  0.00915834,  0.00887752,
        0.00835993,  0.00811404,  0.0077903 ,  0.00742567,  0.00685994,
        0.00661976,  0.00637225,  0.00602515])

In [30]:
X_train_pca = pca.transform(X_train)
X_val_pca = pca.transform(X_val)

In [31]:
print(X_train_pca.shape)
print(X_val_pca.shape)

(33600, 33)
(8400, 33)


In [32]:
classifier = svm.SVC()
classifier.fit(X_train_pca, y_train)
classifier.score(X_val_pca, y_val)

0.97964285714285715